### PR TITLE
Bump LuaJIT

### PR DESCRIPTION
**Pull request by jimman2003**
Used by https://github.com/koreader/koreader-base/pull/1370

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/android-luajit-launcher/307)

### CODE REVIEW

**Review by NiLuJe — APPROVED** [review]

**Comment by pazos** [comment]
Sadly this LuaJIT bump fails to build against arm-v7a ABI. No problem with x86. @NiLuJe could you take a look?. If not I would suggest to revert this commit as changes are fairly minor and it is blocking submodule bumps in front

**Comment by NiLuJe** [comment]
Do you have the exact compiler output?

**Comment by pazos** [comment]
Nevermind. It works now. I have no idea why :smile:

**Comment by NiLuJe** [comment]
Yeah, was going to say it builds in a clean build ;p.

**Comment by Frenzie** [comment]
Also I believe I already tried it a few days ago, too. But sometimes I have
to remove/reset some stuff in that repo; haven't bothered to investigate in
depth.

**Pull request merged**
