### PR TITLE
Tolino Epos 1 warmth lights support

### PR DESCRIPTION
**Pull request by hugleo**
Manufacturer: rakuten kobo inc
    Brand: rakutenkobo
    Model: tolino
    Device: ntx_6sl
    Product: ntx_6sl
    Hardware: e70q20
    Platform: imx6
    Friendly name:
    [test.log](https://github.com/user-attachments/files/17102791/test.log)
    Tolino Epos 1
    Android 4.4
    Tolino Ntx, Freescale/NTX

This change is [Reviewable](https://reviewable.io/reviews/koreader/android-luajit-launcher/513)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Review by pazos — CHANGES_REQUESTED** [review]
The device is already recognized as a `TOLINO_EPOS`, which is a shared definition that applies to EPOS1 and EPOS2. The only change you'll need to apply is the light driver.

Both devices should benefit from Root to Ntx transition.

**Review by hugleo — COMMENTED** [review]
Already is:

```
            return when (DeviceInfo.LIGHTS) {
                DeviceInfo.LightsDevice.NOOK_GL4,
                DeviceInfo.LightsDevice.TOLINO_EPOS -> {
                    logController("TolinoRoot")
                    TolinoRootController()
                }
```

That's because I follow the model from Tolino Shine 3 because for Tolino Epos 1 TolinoRoot doesn't work and the one that works is TolinoNTX

```
// Tolino Shine 3 also has warmth lights, but with ntx_io file
        TOLINO_SHINE3 = BRAND.contentEquals(STR_KOBO)
            && MODEL.contentEquals(STR_TOLINO)
            && DEVICE.contentEquals(STR_NTX)
            && HARDWARE.contentEquals("e60k00")
```

```
                DeviceInfo.LightsDevice.CREMA_0710C,
                DeviceInfo.LightsDevice.CREMA_CARTA_G,
                DeviceInfo.LightsDevice.MEEBOOK_P6,
                DeviceInfo.LightsDevice.RIDI_PAPER_3,
                DeviceInfo.LightsDevice.TOLINO_EPOS1,
                DeviceInfo.LightsDevice.TOLINO_SHINE3,
                DeviceInfo.LightsDevice.TOLINO_VISION4,
                DeviceInfo.LightsDevice.TOLINO_VISION5 -> {
                    logController("TolinoNTX")
                    TolinoNtxController()
                }
```

**Comment by pazos** [comment]
Yes, please move `DeviceInfo.LightsDevice.TOLINO_EPOS` from `TolinoRootController()` to `TolinoNtxController()`

Don't add new identifiers here, Tolino 1 and 2 share epd and lights drivers.

///--///

Or, if you want to document `Epos1`, create a new definition and use that for both lights and epd. Also rename EPOS to EPOS2

**Comment by hugleo** [comment]
> Yes, please move `DeviceInfo.LightsDevice.TOLINO_EPOS` from `TolinoRootController()` to `TolinoNtxController()`
> 
> Don't add new identifiers here, Tolino 1 and 2 share epd and lights drivers.
> 
> ///--///
> 


So, we would do right now then because the following implement exactly like a do :)

            && !HARDWARE.contentEquals("e60k00")
            && !HARDWARE.contentEquals("e60q50")
            && !HARDWARE.contentEquals("e70k00")

Then remove TOLINO_SHINE3, TOLINO_VISION4, TOLINO_VISION5 as well, why not?

> Or, if you want to document `Epos1`, create a new definition and use that for both lights and epd. Also rename EPOS to EPOS2

**Comment by pazos** [comment]
> Then remove TOLINO_SHINE3, TOLINO_VISION4, TOLINO_VISION5 as well, why not?

As I said previously I have no problem with different identifiers for EPOS1 and EPOS2, as long as you use those identifiers to asign proper eink drivers to each one.

The current PR removes the device from being identified as a EPOS, so no longer receives TolinoNTX as its controller.

**Comment by hugleo** [comment]
> > Then remove TOLINO_SHINE3, TOLINO_VISION4, TOLINO_VISION5 as well, why not?
> 
> As I said previously I have no problem with different identifiers for EPOS1 and EPOS2, as long as you use those identifiers to asign proper eink drivers to each one.
> 
> The current PR removes the device from being identified as a EPOS, so no longer receives TolinoNTX as its controller.

For EDP driver is bot being removed because is catched again here MODEL.contentEquals(STR_TOLINO), worth for all TOLINOS:

```
        TOLINO = BRAND.contentEquals(STR_TOLINO) && MODEL.contentEquals("imx50_rdp")
            || MODEL.contentEquals(STR_TOLINO) && (DEVICE.contentEquals("tolino_vision2")
            || DEVICE.contentEquals(STR_NTX))
```

In EPDFactory.kt there is no TOLINO_EPOS.

Seems like  TOLINO_EPOS is behaving like a generic light driver because is used only in LightsFactory.kt for TolinoRootController.

**Comment by pazos** [comment]
> For EDP driver is not being removed because is catched again here MODEL.contentEquals(STR_TOLINO), worth for all TOLINOS:
EDIT: Is not catched, I misread some parentheses

Ah, my bad. You're right. 

Let me see if I can search if the EPOS2 was reported once and split those two devices properly without `TOLINO_EPOS` being the tolino that's not all these other modern tolinos.

**Comment by pazos** [comment]
Nope. It turns out it was a major @zwim contribution. AFAICT he no longer has the device.

As far as this PR: please do as you like:

1. Stick with `TOLINO_EPOS` for both 1 and 2 and move it to "lights ntx"
2. Create the new `TOLINO_EPOS1` as you did, rename the old one to `TOLINO_EPOS2` and move it to "lights ntx" too.
3. Create the new `TOLINO_EPOS1` as you did, remove all the references to `TOLINO_EPOS` and wait for a future report that lets us to identify that device properly.

**Comment by hugleo** [comment]
> Nope. It turns out it was a major @zwim contribution. AFAICT he no longer has the device.
> 
> As far as this PR: please do as you like:
> 
>     1. Stick with `TOLINO_EPOS` for both 1 and 2 and move it to "lights ntx"
> 
>     2. Create the new `TOLINO_EPOS1` as you did, rename the old one to `TOLINO_EPOS2` and move it to "lights ntx" too.
> 
>     3. Create the new `TOLINO_EPOS1` as you did, remove all the references to `TOLINO_EPOS` and wait for a future report that lets us to identify that device properly.

3

**Review by pazos — APPROVED** [review]

**Comment by Frenzie** [comment]
Ready to merge?

**Comment by hugleo** [comment]
Listo

**Comment by pazos** [comment]
Yep

**Pull request merged**
