### PR TITLE
int to bool

### PR DESCRIPTION
**Pull request by pazos**
Since we have `JNI:callBooleanMethod`.

~~Untested yet.~~

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/android-luajit-launcher/268)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
Hm, how come we didn't do this before? JNI update or something?

**Comment by pazos** [comment]
> Hm, how come we didn't do this before? JNI update or something?

both `callBooleanMethod` and the first usage of `return callIntMethod == 1` are in https://github.com/koreader/android-luajit-launcher/commit/d0e2274673d683fbbd7e6a2e11d46f2b60b440d5. Since then I think we basically copy-pasted code based on other lua functions.

**Comment by pazos** [comment]
@Frenzie: now tested. It works fine :tada: 

Added a few fixes for bugs in previous commits. I will rebase when you think is ready!

**Review by Frenzie — APPROVED** [review]
All good to me, that splashscreen thing is a bit random in this PR though. :-P

**Comment by pazos** [comment]
> All good to me, that splashscreen thing is a bit random in this PR though. :-P

Indeed. Also now I find that some true/false values are swapped. No idea why. I will split this PR in two and wait a bit for the int -> bool changes. The rest of things work fine and can be merged soon.

**Comment by pazos** [comment]
Something fishy happens with this commit. 1 used to be true and ~= 1 false. Now all things are inversed :cry:

**Comment by pazos** [comment]
> Something fishy happens with this commit. 1 used to be true and ~= 1 false. Now all things are inversed

It turns out that any boolean was true, because jboolean is uint8_t and gets casted to a lua number, and no number is nil :) 

Works fine now.

**Pull request merged**
