### PR TITLE
simplify `FileExtensions.uncompress` implementation

### PR DESCRIPTION
**Pull request by benoit-pierre**
This change is [Reviewable](https://reviewable.io/reviews/koreader/android-luajit-launcher/418)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
Fine by me though I don't know that I necessarily agree with the description.

**Comment by benoit-pierre** [comment]
How would you describe it?

**Comment by Frenzie** [comment]
"Use Apache IOUtils in FileExtensions.uncompress" :-)

It's a simplification of sorts if you're doing this multiple times but here it's just a minor abstraction for the same thing. But no matter.

**Comment by pazos** [comment]
It's easier to read, so simplification works for me :)

**Review by pazos — APPROVED** [review]

**Pull request merged**
