### PR TITLE
add Onyx Poke 4 lite

### PR DESCRIPTION
**Pull request by luutuankiet**
This change is [Reviewable](https://reviewable.io/reviews/koreader/android-luajit-launcher/406)

### CODE REVIEW

**Review by luutuankiet — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/android-luajit-launcher/406)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @luutuankiet)

**Review by pazos — APPROVED** [review]
LGTM

Thank you!

**Comment by luutuankiet** [comment]
hi @pazos I assume we'd have this update in Koreader's next March release on March right ?

**Comment by pazos** [comment]
Yes.

Also, hopefully, in a couple of days' nightly :)

**Pull request merged**
