### PR TITLE
Update LuaJIT mcode hack

### PR DESCRIPTION
**Pull request by NiLuJe**
* Fix pointer arithmetic on !x86/!x64

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/android-luajit-launcher/287)

### CODE REVIEW

**Comment by NiLuJe** [comment]
This one shouldn't have been an issue on Android, but it could conceivably have been.

On the other hand, it was completely broken on plain Linux with the default settings ;).

**Review by pazos — APPROVED** [review]
I can pretend I understand what you coded but I won't pretend I'm going to review a diff of a patch :smile:

**Review by Frenzie — APPROVED** [review]
@pazos Well, I'm not sure I fully understand the issue but it doesn't look like it should break anything. :-D

**Comment by NiLuJe** [comment]
All the pointers in question are `MCode *`, and... https://github.com/LuaJIT/LuaJIT/blob/1e66d0f9e6698fdee672c40a9a5b4159c9254091/src/lj_jit.h#L170-L175

So, on arm, it's an `uint32_t*`, which means instead of adding `size` bytes, we were adding `size * 4` bytes ;).

**Pull request merged**
