### PR TITLE
support for Onyx Nova3 Color and Onyx Nova Air

### PR DESCRIPTION
**Pull request by pazos**
https://github.com/koreader/koreader/issues/8482

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/android-luajit-launcher/345)

### CODE REVIEW

**Comment by Frenzie** [comment]
Cool :)

**Comment by deep-dark-blue** [comment]
Hi there
I installed the latest nightly on my Onyx Nova Air and it crashes instantly when starting koreader. [it reports some issues getting the correct warmth-values...] As I am no pro in coding nor in github, I am not sure where to report this?

**Comment by Frenzie** [comment]
The latest nightly or yesterday's nightly? Big difference. ;-)

https://github.com/koreader/koreader/pull/8593

**Comment by deep-dark-blue** [comment]
yesterday's nightly [koreader-android-arm-v2021.12.1-7-g16228229_2021-12-25.apk]

--------- beginning of crash
12-27 14:00:12.771 E/AndroidRuntime(21655): FATAL EXCEPTION: Thread-47
12-27 14:00:12.771 E/AndroidRuntime(21655): Process: org.koreader.launcher, PID: 21655
12-27 14:00:12.771 E/AndroidRuntime(21655): java.lang.ExceptionInInitializerError
12-27 14:00:12.771 E/AndroidRuntime(21655): 	at org.koreader.launcher.device.lights.OnyxWarmthController.getWarmth(OnyxWarmthController.kt:1)
12-27 14:00:12.771 E/AndroidRuntime(21655): 	at org.koreader.launcher.MainActivity.getScreenWarmth(MainActivity.kt:1)
12-27 14:00:12.771 E/AndroidRuntime(21655): Caused by: java.lang.NoSuchMethodException: android.onyx.hardware.DeviceController.setWarmLightDeviceValue [class android.content.Context, int]
12-27 14:00:12.771 E/AndroidRuntime(21655): 	at java.lang.Class.getMethod(Class.java:2072)
12-27 14:00:12.771 E/AndroidRuntime(21655): 	at java.lang.Class.getMethod(Class.java:1693)
12-27 14:00:12.771 E/AndroidRuntime(21655): 	at org.koreader.launcher.device.lights.FrontLight.<clinit>(OnyxWarmthController.kt:2)
12-27 14:00:12.771 E/AndroidRuntime(21655): 	... 2 more
12-27 14:01:28.699 E/AndroidRuntime(21905): FATAL EXCEPTION: Thread-46
12-27 14:01:28.699 E/AndroidRuntime(21905): Process: org.koreader.launcher, PID: 21905
12-27 14:01:28.699 E/AndroidRuntime(21905): java.lang.ExceptionInInitializerError
12-27 14:01:28.699 E/AndroidRuntime(21905): 	at org.koreader.launcher.device.lights.OnyxWarmthController.getWarmth(OnyxWarmthController.kt:1)
12-27 14:01:28.699 E/AndroidRuntime(21905): 	at org.koreader.launcher.MainActivity.getScreenWarmth(MainActivity.kt:1)
12-27 14:01:28.699 E/AndroidRuntime(21905): Caused by: java.lang.NoSuchMethodException: android.onyx.hardware.DeviceController.setWarmLightDeviceValue [class android.content.Context, int]
12-27 14:01:28.699 E/AndroidRuntime(21905): 	at java.lang.Class.getMethod(Class.java:2072)
12-27 14:01:28.699 E/AndroidRuntime(21905): 	at java.lang.Class.getMethod(Class.java:1693)
12-27 14:01:28.699 E/AndroidRuntime(21905): 	at org.koreader.launcher.device.lights.FrontLight.<clinit>(OnyxWarmthController.kt:2)
12-27 14:01:28.699 E/AndroidRuntime(21905): 	... 2 more

**Comment by deep-dark-blue** [comment]
ok... got it - yestarday's nightliy works! [koreader-android-arm-v2021.12.1-13-g4b5ea119_2021-12-26.apk] - it was displayed in the middle of the list and not at the end... ;)

**Comment by Frenzie** [comment]
Well, that's the latest nightly — by yesterday's nightly I was referring to v2021.12.1-7-g16228229_2021-12-25 (which "should" probably crash). But regardless. ;-)

**Pull request merged**
