### PR TITLE
EPD & Lights drivers for Xiaomi RK3566 based devices

### PR DESCRIPTION
**Pull request by jkl16**
- Added EPD driver implementing full refresh for Xiaomi 7 Reader. Refresh is using mode configured in System UI. 
- Added Lights & Warmth driver implementing _getting_ & _setting_ values, however _setting_ is not enabled since it requires root.

I have provided more details in https://github.com/koreader/android-luajit-launcher/issues/477

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/android-luajit-launcher/478)

### CODE REVIEW

**Comment by jkl16** [comment]
Since complexity check is failing, should I split out EPD and light changes to a separate PRs?

**Comment by Frenzie** [comment]
Nah, that check seems kind of dumb, at least in the context of this PR.

**Comment by pazos** [comment]
> Added Lights & Warmth driver implementing getting & setting values, however setting is not enabled since it requires root.

I'm not very fan of this. It would be better to use an Intent to launch the native dialog used by the system, if something like this exists. Gestures won't work but at least the dialog would be useful to change levels.

Until now all drivers rely on our own widget, so we need a little change to make possible to call external widgets instead.

What do you think, @jkl16?

**Comment by jkl16** [comment]
In the device that I own, brightness & warm levels can only be controlled from native Android notification panel. It looks as on the following photo:


The panel can be accessed when running KOReader at any time by pulling it down from the top edge.  From UX perspective that seems good enough, so maybe there is no need to implement that part at all.
The biggest issue is the fact that the notification panel gesture collides with KOReader top menubar.

**Comment by Frenzie** [comment]
> From UX perspective that seems good enough, so maybe there is no need to implement that part at all.

Better not indeed.

**Comment by jakkli-mend** [comment]
Then based on the discussion I removed all lights related code from the branch.

**Comment by jkl16** [comment]
Then based on the discussion I removed all lights related code from the branch.

**Review by Frenzie — APPROVED** [review]

**Review by pazos — APPROVED** [review]
lgtm, thanks!

**Comment by pazos** [comment]
> The biggest issue is the fact that the notification panel gesture collides with KOReader top menubar.

You can setup KO top menu to be activated only when tapping and use the swipe gesture to activate system menu.

**Pull request merged**
