### PR TITLE
Handle 64-bit binaries in elf/dl

### PR DESCRIPTION
**Pull request by NiLuJe**
That should hopefully have been the last non-toolchain-related hurdle for an aarch64 build ;).

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/android-luajit-launcher/289)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
If you say so. :-P

**Comment by pazos** [comment]
> That should hopefully have been the last non-toolchain-related hurdle for an aarch64 build ;).

The standalone example worked before, but I guess it was because LuaJIT was part of the main shared lib?

**Review by pazos — APPROVED** [review]

**Comment by NiLuJe** [comment]
@pazos: What standalone example? ^^.

(The two formats are very similar, there's a vague chance using the Elf32 data types *on a 64-bit host* mostly worked for what we were doing).

**Comment by Frenzie** [comment]
@NiLuJe examples/helloWorld I imagine

**Comment by NiLuJe** [comment]
Yep, confirmed that it failed on Elf64 files before (random test on an x64 binary ;p).

```
luajit utils/print_dt_needed.lua /usr/bin/ag
luajit: utils/elf.lua:164: no .dynstr section in /usr/bin/ag
stack traceback:
        [C]: in function 'assert'
        utils/elf.lua:164: in function 'dlneeds'
        utils/print_dt_needed.lua:14: in main chunk
        [C]: at 0x55d8662fdfc0
```

```
needed => libpcre.so.1 (1 of 5) <= /usr/bin/ag
needed => liblzma.so.5 (2 of 5) <= /usr/bin/ag
needed => libz.so.1 (3 of 5) <= /usr/bin/ag
needed => libpthread.so.0 (4 of 5) <= /usr/bin/ag
needed => libc.so.6 (5 of 5) <= /usr/bin/ag
```

**Comment by NiLuJe** [comment]
Tweaked the logging and asserts some more, and actually tested on a real device ;p.

**Pull request merged**
