### PR TITLE
Change Onyx Page to adb driver

### PR DESCRIPTION
**Pull request by hugleo**
This change is [Reviewable](https://reviewable.io/reviews/koreader/android-luajit-launcher/493)

### CODE REVIEW

**Comment by hugleo** [comment]
@ilyats You can test this APK to see if it is working properly before we merge:

https://we.tl/t-SrCF9QONhs

**Comment by thetyrantcbass** [comment]
Thank you for the pointer. With this build, I enabled Autowarmth and it worked immediately.

**Comment by hugleo** [comment]
@pazos Looks fine!

**Comment by ilyats** [comment]
> @ilyats You can test this APK to see if it is working properly before we merge:
> 
> https://we.tl/t-ueUZUiDWM0

It works

**Review by ilyats — APPROVED** [review]
It works

**Review by ilyats — APPROVED** [review]

**Comment by ilyats** [comment]
Can somebody commit it? @pazos

**Comment by ilyats** [comment]
@pazos thank you very much

**Comment by pazos** [comment]
yay, sorry about the delay, @ilyats

**Comment by hugleo** [comment]
Yes,

Need a commit to bump in the main project.

If someone not beat me I'll make a PR to support fewer more devices before that.

**Pull request merged**
