### PR TITLE
Add onyx max

### PR DESCRIPTION
**Pull request by pazos**
https://github.com/koreader/koreader/issues/8482

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/android-luajit-launcher/348)

### CODE REVIEW

**Comment by jonch919** [comment]
Thank you, much appreciated!

**Review by Frenzie — APPROVED** [review]
Cool!

**Comment by jonch919** [comment]
Should this be in the dev builds now? I still don't see the refresh options under e-ink settings. (Latest dev build)
Or do I have to install anything else besides koreader?
Sorry, but I have no idea how GitHub works with commits, merging, etc. 
Thanks,
@pazos

**Comment by pazos** [comment]
Did you tryhttps://ota.koreader.rocks/koreader-android-latest-nightly ?

It was merged yesterday

**Comment by jonch919** [comment]
I'll check when I'm at home in a couple of hours. I probably  have the previous version that I got yesterday.

**Comment by jonch919** [comment]
It works now, thanks!

**Pull request merged**
