### PR TITLE
Remove support for legacy/deprecated methods

### PR DESCRIPTION
**Pull request by pazos**
* Remove support for legacy methods (used by android <= 4.2)
* Fix a few warnings on drivers
* Remove unused definitions
* Idiomatic kotlin

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/android-luajit-launcher/425)

### CODE REVIEW

**Comment by pazos** [comment]
Also pinging @hugleo for a review.

**Review by Frenzie — APPROVED** [review]
Removing the old stuff is nice, not really sure what you mean by idiomatic Kotlin but lgtm

**Comment by pazos** [comment]
> not really sure what you mean by idiomatic Kotlin but lgtm

```kotlin
return if (x) 
    true
else
    false
```

instead of
```kotlin
if (x)
    return true
else
    return false
```

And a few other things: string templates, null checks via `let` ...

**Review by hugleo — APPROVED** [review]
LGTM.
Tested in some devices android 6, 11, 13

**Pull request merged**
