### PR TITLE
archiveUtils fixes

### PR DESCRIPTION
**Pull request by pazos**
Fix for some dicts that have no dir entries.

Ie:

instead of
```
someDict/
someDict/foo
someDict/bar
```

have:

```
someDict/foo
someDict/bar
```

It also adds some robustness in the extraction and an option to delete the container once sucesfully uncompressed. The later is disabled by default to match the behaviour of other platforms.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/android-luajit-launcher/274)

### CODE REVIEW

**Comment by pazos** [comment]
@Frenzie: Did I miss the 2020.12 deadline? :cry: 

Is not a very important change TBH, but some people call the monthly release "stable" and I would want to honor that people ;)

**Review by Frenzie — APPROVED** [review]
Looks fine to me. 

Wrt a release, I just won't tag & upload anything today then so it can get a day or two of testing.

**Comment by pazos** [comment]
> Wrt a release, I just won't tag & upload anything today then so it can get a day or two of testing.

I tested manually against some dicts that have no dir entries (english -> gcide, for instance). 

I think I can write an unit test that downloads and try to uncompress all the dictionaries in https://github.com/koreader/koreader/blob/master/frontend/ui/data/dictionaries.lua.But that needs some refactor!

**Comment by Frenzie** [comment]
All seems a touch bandwidth wasting? ;-)

**Comment by pazos** [comment]
> All seems a touch bandwidth wasting? ;-)

Yup. Probably with two single cases we're fine.

## normal

```
tar -tzf stardict-german-czech_20161201.orig.tar.gz 
stardict-german-czech-20161201/
stardict-german-czech-20161201/german-czech.ifo
stardict-german-czech-20161201/german-czech.idx
stardict-german-czech-20161201/czech-german.ifo
stardict-german-czech-20161201/czech-german.idx
stardict-german-czech-20161201/README
stardict-german-czech-20161201/czech-german.dict.dz
stardict-german-czech-20161201/german-czech.dict.dz
```

## broken / unordered

```
tar -tzf gcide.tar.gz 
gcide/stardict.idx
gcide/stardict.dict.dz
gcide/
gcide/stardict.syn
gcide/stardict.ifo
```

But I don't know how to generate a tar file that showcases the second condition. Any hint @Frenzie @NiLuJe

Random tests gave me the impression that almost half of the dicts are broken that way.

**Comment by Frenzie** [comment]
Probably with a simple `touch`? (Creation order.)

**Pull request merged**
