### PR TITLE
Test tooltip

### PR DESCRIPTION
**Pull request by hugleo**
tool-tip

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/android-luajit-launcher/461)

### CODE REVIEW

**Comment by pazos** [comment]
I'm not sure if the reason to make the tooltip a part of the dialog is to show the tooltip over the main program. In that case could you share a screenshot?

If not please build the tip as part of testactivity

**Comment by hugleo** [comment]
> If not please build the tip as part of testactivity

Much better, thanks!

**Comment by pazos** [comment]
@hugleo: sorry, I forgot about this PR.

Could you rebase on top of master?

**Comment by hugleo** [comment]
> @hugleo: sorry, I forgot about this PR.
> 
> Could you rebase on top of master?

there

**Review by pazos — APPROVED** [review]
great!
thank you!

**Pull request merged**
