### PR TITLE
Update LuaJIT

### PR DESCRIPTION
**Pull request by NiLuJe**
re https://github.com/koreader/koreader-base/pull/1133

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/android-luajit-launcher/236)

### CODE REVIEW

**Comment by Frenzie** [comment]
@pazos Not necessarily, the patch made it so that the x86 build actually worked on my x86 ASUS Zenfone 2. But if you just get it into a nightly build I can check on it. (I could also build it myself but not right now anyway.)

**Comment by Frenzie** [comment]
@pazos But shouldn't it just need a minor update of a few lines?

**Comment by pazos** [comment]
> But shouldn't it just need a minor update of a few lines?

Most of things patched are no longer there. I didn't take a deep look. Just rebased #235 and saw the issue.

**Comment by NiLuJe** [comment]
Ah. Forgot the patch ;p. It's updated in the base pr, I just forgot it hero;).

**Pull request merged**
