### PR TITLE
Onyx Tab Ultra Color support

### PR DESCRIPTION
**Pull request by hugleo**
Add support to Onyx Tab Ultra Color

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/android-luajit-launcher/431)

### CODE REVIEW

**Comment by pazos** [comment]
Hey, thanks for the patch.

Color devices need to specify that too, so won't loose color when being treated as EinkDevices.

See https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt#L686

**Comment by hugleo** [comment]
> Hey, thanks for the patch.
> 
> Color devices need to specify that too, so won't loose color when being treated as EinkDevices.
> 
> See https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt#L686

Bu it's already doing in my patch:

EinkDevice.ONYX_TAB_ULTRA_C -> true

**Comment by pazos** [comment]
ap, sorry.

I didn't catch it after a quick skim :p

All good then :)

**Review by pazos — APPROVED** [review]

**Comment by pazos** [comment]
@hugleo: I would like to merge this one, too. Please remove the draft flag :)

**Comment by hugleo** [comment]
Can be merged. Unfortunately no official build support for lights at the moment :(
See : https://github.com/koreader/android-luajit-launcher/pull/436 for more information.

**Pull request merged**
