### PR TITLE
Fix & enable HW rotation on notched devices on P+

### PR DESCRIPTION
**Pull request by NiLuJe**
Looks simple enough (he said, hopefully ;p) :).

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/android-luajit-launcher/288)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Ah. Knew it was too easy: this excludes the status bar, too.

**Review by pazos — COMMENTED** [review]
As you know `getScreenSizeWithConstraints(activity)` only works on pre KitKat devices (apis 17 & 18) and it is completely deprecated in immersive mode (apis19+).

Since legacy APIs doesn't use HW rotation I think it is safe to ignore `getScreenAvailableWidth` et al.

**Comment by NiLuJe** [comment]
Note to self: nav bar, not status bar.

**Comment by NiLuJe** [comment]
> As you know `getScreenSizeWithConstraints(activity)` only works on pre KitKat devices (apis 17 & 18) and it is completely deprecated in immersive mode (apis19+).
> 
> Since legacy APIs doesn't use HW rotation I think it is safe to ignore `getScreenAvailableWidth` et al.

Err, the only thing it does is using `getMetrics` instead of `getRealMetrics`. AFAICT, that's very much [not deprecated until SDK 30](https://developer.android.com/reference/android/view/Display#getMetrics(android.util.DisplayMetrics)), and it indeed worked perfectly fine on my API 29 phone. It just happens to *also* exclude the nav bar, which is a problem ^^.

Speaking of, the [SDK 30 variant](https://developer.android.com/reference/android/view/WindowMetrics#getBounds()) has a code excerpt to do that manually, and it appears to be able to tell display cutout apart from the nav bar ;).

**Comment by pazos** [comment]
@NiLuJe: You're right. I was talking about our usage :P. As we always enable immersive mode in KitKat+ devices, we don't need `getMetrics` there. It could be relevant for https://github.com/koreader/android-luajit-launcher/issues/238, but there're better ways to retrieve screen size on [each surface change](https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/MainActivity.kt#L59-L62)

But having that available doesn't hurt either. :+1:

**Review by pazos — APPROVED** [review]

**Pull request merged**
