### PR TITLE
Support for a bunch of rockchip devices

### PR DESCRIPTION
**Pull request by hugleo**
Device info:
Manufacturer: haoqing
Brand: haoqing
Model: m6
Device: m6
Product: rk3566_eink
Hardware: rk30board
Platform: rk356x

Working EPD Driver: RK3566

Device info:
Manufacturer: haoqing
Brand: haoqing
Model: m7
Device: m7
Product: rk3566_eink
Hardware: rk30board
Platform: rk356x

Working EPD Driver: RK3566

Device info:
Manufacturer: rockchip
Brand: rockchip
Model: moaanmix7
Device: rk3566_eink
Product: moaan
Hardware: rk30board
Platform: rk356x

Working EPD Driver: RK3566

Device info:
Manufacturer: rockchip
Brand: rockchip
Model: inkpalmplus
Device: rk3566_eink
Product: moaan
Hardware: rk30board
Platform: rk356x

Working EPD Driver: RK3566

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/android-luajit-launcher/483)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by Bluemoondragon07** [comment]
Are these changes in effect for recent nightlies of KOreader? The Meebook M7 is still registered as an unsupported device in the most recent nightly release.

**Comment by benoit-pierre** [comment]
Yes, since v2024.04-206-gb7fc048bb.

**Comment by hugleo** [comment]
Nothing was removed here. @Bluemoondragon07, can you run the KOReader eink test tool to confirm your device? 
Follow instructions here: https://github.com/koreader/koreader/issues/8482

**Comment by Bluemoondragon07** [comment]
The Rockchip rk3566 works when I test it. For some reason, the device just doesn't register as supported. I will see if downloading the last stable release, 2024.07, fixes anything.

**Comment by Bluemoondragon07** [comment]
Uninstalling and reinstalling 2024.07 didn't do the trick, unfortunately.

**Comment by benoit-pierre** [comment]
Could it be some sort of trailing whitespace in some fields that would trip one or more of the string equality tests?

**Comment by Bluemoondragon07** [comment]
So,  with the latest nightly, the Meebook M7 now shows up as supported, but the full screen refresh function does not work using gestures. Setting the page refresh in e-ink settings to refresh every page, nothing happens. 



So, still can't trigger refreshes yet, but it's showing up as supported now. 

Also, I tried in both regal/normal mode and A2/fast mode.

**Comment by hugleo** [comment]
> So, with the latest nightly, the Meebook M7 now shows up as supported, but the full screen refresh function does not work using gestures. Setting the page refresh in e-ink settings to refresh every page, nothing happens.
> 
> 
> 
> So, still can't trigger refreshes yet, but it's showing up as supported now.
> 
> Also, I tried in both regal/normal mode and A2/fast mode.

in eink-test is Working EPD Driver RK3566 or another one?

**Comment by Bluemoondragon07** [comment]
@hugleo Yes, in compatibility test Rockchip Rk3566  triggers a full refresh in all refresh modes.

**Comment by Bluemoondragon07** [comment]
https://github.com/user-attachments/assets/3ee0dd09-30f7-4b33-848b-56ce66e604db

**Comment by hugleo** [comment]
@pazos One of those hard cases that works on E Ink but not KOReader. Any advice?

**Comment by Bluemoondragon07** [comment]
It might have something to do with KOreader not using typical Android elements? I can't get anything in KOreader, except in compatibility test, to trigger a refresh, even with native device settings. In most apps, such as Moon Reader, if I have the device refresh rate set to 1, then every tap on an Android element or app event triggered by a physical button press causes a refresh.

When I go into compatibility test, I know it must be using Android elements, because any button I press there will follow the device refresh rate settings. Of course, pressing the  Rk3566 test will make it refresh every time anyway regardless of device settings. But with that refresh-rate-of-1 setting, any of those buttons trigger a refresh if I tap on them. 

But as soon as I exit that compatibility test in KOreader, there is nothing within the app that can cause a refresh. I can only refresh it manually through the OS from there.

**Comment by Frenzie** [comment]
> But with that refresh-rate-of-1 setting, any of those buttons trigger a refresh if I tap on them.

That's a very irrelevant test then. ;-) Try it with the system's reset setting to something significantly higher than 1.

**Comment by Bluemoondragon07** [comment]
@Frenzie my tests have been with different refresh rates, I was just giving a specific example of how the UI in compatibility test reacts to device system refresh rate but the rest of the app does not. The RK3566 test always refreshes the screen, regardless of refresh rate or even refresh mode. It's just that I notice other buttons in the test can trigger system refreshes because they are registered as real Android buttons.

**Pull request merged**
